HomeWork/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hw_23Nov.urls')),
    path('', include('hw_23Nov_part2.urls')),
]

TaskBoard/urls.py
from django.contrib import admin
from django.urls import path

from TaskBoard.views import create_task, get_all_tasks, about_task, delete_task, save_subscribes, create_icecream, \
    get_icecream, edit_task

app_name = 'taskboard'

urlpatterns = [
    path('', get_all_tasks, name='all_tasks'),
    path('create_task/', create_task, name='create_task'),
    path('about_task/<int:task_id>/', about_task, name='about_task'),
    path('delete_task/<int:task_id>/', delete_task, name='delete_task'),
    path('subscribe/', save_subscribes, name='subscribe'),
    path('create_icecream/', create_icecream, name='create_icecream'),
    path('icecream/', get_icecream, name='icecream'),
    path('edit/', edit_task, name='edit_task'),

]

TaskManager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('TaskBoard.urls', namespace='taskboard'))

]
urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

accounts/urls.py
from django.urls import path, re_path
from django.contrib.auth.views import LoginView

from .views import UserCreateView, AllUsersView, UserDetailView, UsersByPeriodView, UserLoginView, reset_pass, new_pass

app_name = 'accounts'
urlpatterns = [
    re_path(r'^r\w{2}/$', UserCreateView.as_view(), name='registration'),
    re_path(r'^l\w*/$', UserLoginView.as_view(), name='login'),
    path('reset/', reset_pass, name='reset'),
    path('new_pass/<int:pk>/', new_pass, name='new_pass'),

    path('users/', AllUsersView.as_view(), name='users'),
    path('get_period/<int:year>/<int:month>/', UsersByPeriodView.as_view(), name='period'),
    path('userdetail/<int:user_id>/', UserDetailView.as_view(), name='user_detail')
]

bboard/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, re_path
from django.views.decorators.http import condition
from django.views.generic import ArchiveIndexView

from bboard.models import Bb
from bboard.views import BbCreateView, Categorylist, BbDetail, CreateComment, DeleteComment, AboutUs, Contacts, \
     BbRedirectView, BbEditView, edit, rubrics, bbs, Search, index, test_email, is_updated


app_name = 'bboard'

cache_page: object
urlpatterns = [
    re_path(r'^add/$', BbCreateView.as_view(), name='add'),
    re_path(r'^detail/(?P<bb_id>[0-9]+)/$', BbDetail.as_view(), name='detail'),
    path('rubrics/', rubrics, name='rubrics'),
    re_path(r'^rubric/(?P<rubric_id>[0-9]+)/$', Categorylist.as_view(), name='by_rubric'),
    re_path(r'^$', index, name='index'),
    re_path(r'^a\w{3}t/$', AboutUs.as_view(), name='about'),
    re_path(r'^c\w{6}s/$', Contacts.as_view(), name='contacts'),
    re_path(r'^create/(?P<bb_id>[0-9]+)/$', CreateComment.as_view(), name='c_create'),
    re_path(r'^delete/(?P<comment_id>[0-9]+)/(?P<bb_id>[0-9]+)/$', DeleteComment.as_view(), name='delete_comment'),
    path('update/<int:pk>/', edit, name='update'),
    path('bbs/<int:rubric_id>/', bbs, name='bbs'),
    path('year/<int:year>/', BbRedirectView.as_view(), name='redirect'),
    # path('<int:year>/<int:month>/', BbMonthView.as_view(), name='month'),
    path('mail/', test_email, name='test_email'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),



    path('search/', Search, name='search')
]

samplesite/urls.py
from django.contrib import admin
from django.urls import path,  include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bboard.urls', namespace='bboard')),
    path('authorization/', include('accounts.urls', namespace='accounts'))

]

urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

templates/includes/css_src.html
{% load static %}
<link rel="icon" href="{% static 'img/core-img/favicon.ico' %}">
<link rel="stylesheet" href="{% static 'css/core-style.css' %}">
<link rel="stylesheet" href="{% static 'style.css' %}">

templates/includes/footer.html
{% load static %}
    <!-- ##### Footer Area Start ##### -->
    <footer class="footer_area clearfix">
        <div class="container">
            <div class="row align-items-center">
                <!-- Single Widget Area -->
                <div class="col-12 col-lg-4">
                    <div class="single_widget_area">
                        <!-- Logo -->
                        <div class="footer-logo mr-50">
                            <a href="{% url 'taskboard:all_tasks' %}"><img src="{% static 'img/core-img/logo2.png' %}"></a>
                        </div>
                        <!-- Copywrite Text -->
                        <p class="copywrite"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                    </div>
                </div>
                <!-- Single Widget Area -->
                <div class="col-12 col-lg-8">
                    <div class="single_widget_area">
                        <!-- Footer Menu -->
                        <div class="footer_menu">
                            <nav class="navbar navbar-expand-lg justify-content-end">
                                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#footerNavContent" aria-controls="footerNavContent" aria-expanded="false" aria-label="Toggle navigation"><i class="fa fa-bars"></i></button>
                                <div class="collapse navbar-collapse" id="footerNavContent">
                                    <ul class="navbar-nav ml-auto">
                                        <li class="nav-item active">
                                            <a class="nav-link" href="../../../../../Downloads/amado/index.html"></a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="../../../../../Downloads/amado/shop.html"></a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="../../../../../Downloads/amado/product-details.html"></a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="cart.html"></a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="../../../../../Downloads/amado/checkout.html"></a>
                                        </li>
                                    </ul>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- ##### Footer Area End ##### -->

templates/includes/head.html
{% load static %}
<head>
    {% include "includes/meta.html" %}
    {% include "includes/title.html" %}
    {% include "includes/css_src.html" %}
</head>

templates/includes/header.html
{% load static %}
<header class=" header-area clearfix">
    <!-- Close Icon -->
    <div class="nav-close">
        <i class="fa fa-close" aria-hidden="true"></i>
    </div>
    <!-- Logo -->
    <div class="logo">
        <a href="{% url 'taskboard:all_tasks' %}"><img src="{% static 'img/core-img/logo.png' %}"></a>
    </div>
    <!-- Amado Nav -->
    {% include "includes/navbar.html" %}
</header>

templates/includes/inc_main_menu.html
<div class = "menu">
    {% if request.user.is_authenticated %}
        <a href="{% url 'bboard:index' %}">На главную</a>
        <a href="{% url 'bboard:add' %}">Подать объявление</a>
        <a href="{% url 'accounts:registration' %}">Регистрация</a>
        <a href="{% url 'accounts:login' %}">Войти</a>
        <p>Текущий пользователь:{{ request.user.username|upper }}</p>
        <a href="{% url 'bboard:logout' %}">Выйти</a>
    {% else %}
        <a href="{% url 'bboard:index' %}">На главную</a>
        <a href="{% url 'bboard:add' %}">Подать объявление</a>
        <a href="{% url 'accounts:registration' %}">Регистрация</a>
        <a href="{% url 'accounts:login' %}">Войти</a>
        <p>Текущий пользователь:ГОСТЬ</p>
        <a href="{% url 'bboard:logout' %}">Выйти</a>
    {% endif %}
</div>

templates/includes/inc_paginator.html
{% load bootstrap4 %}

{% bootstrap_pagination page_obj pages_to_show=3 size="small" %}

{% if page_obj.has_other_pages %}
    <nav aria-label="pagination">
        <ul class="pagination">

            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link"
                       href="?page={{ page_obj.previous_page_number }}">Назад</a>
                </li>
            {% endif %}
        
            {% for p in page_obj.paginator.page_range %}
                {% if not p == page_obj.number %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ p }}">{{ p }}</a>
                </li>
                {% else %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link disabled bg-primary text-light"
                       href="?page={{ p }}">{{ p }}</a>
                </li>
                {% endif %}
            {% endfor %}
        
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link"
                       href="?page={{ page_obj.next_page_number }}">Вперёд</a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}

templates/includes/js_src.html
{% load static %}
<!-- ##### jQuery (Necessary for All JavaScript Plugins) ##### -->
<script src="{% static 'js/jquery/jquery-2.2.4.min.js' %}"></script>
<!-- Popper js -->
<script src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap js -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- Plugins js -->
<script src="{% static 'js/plugins.js' %}"></script>
<!-- Active js -->
<script src="{% static 'js/active.js' %}"></script>

<script src="{% static 'common.js' %}"></script>

templates/includes/main_wrapper.html
<div class="main-content-wrapper d-flex clearfix">
    {% include "includes/header.html" %}
    {% include "includes/main_content.html" %}
    {% if title == 'All tasks' %}
        {% include "includes/paginator.html" %}
    {% endif %}
</div>

templates/includes/meta.html
<meta charset="UTF-8">
<meta name="description" content="">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

templates/includes/navbar.html
<nav class="amado-nav">
    <ul>
        {% if active_page == 'all tasks' %}
            <li class="active"><a href="{% url 'taskboard:all_tasks' %}">All tasks</a></li>
            <li class=""><a href="{% url 'taskboard:create_task' %}">Create task</a></li>
            <li class=""><a href="{% url 'taskboard:edit_task' %}">Edit task</a></li>
            <li class=""><a href="{% url 'taskboard:icecream' %}">Icecream</a></li>
            <li class=""><a href="{% url 'taskboard:create_icecream' %}">Create Icecream</a></li>

        {% elif active_page == 'create task' %}
            <li class=""><a href="{% url 'taskboard:all_tasks' %}">All tasks</a></li>
            <li class="active"><a href="{% url 'taskboard:create_task' %}">Create task</a></li>
            <li class=""><a href="{% url 'taskboard:edit_task' %}">Edit task</a></li>
            <li class=""><a href="{% url 'taskboard:icecream' %}">Icecream</a></li>
            <li class=""><a href="{% url 'taskboard:create_icecream' %}">Create Icecream</a></li>

        {% elif active_page == 'icecream' %}
            <li class=""><a href="{% url 'taskboard:all_tasks' %}">All tasks</a></li>
            <li class=""><a href="{% url 'taskboard:create_task' %}">Create task</a></li>
            <li class=""><a href="{% url 'taskboard:edit_task' %}">Edit task</a></li>
            <li class="active"><a href="{% url 'taskboard:icecream' %}">Icecream</a></li>
            <li class=""><a href="{% url 'taskboard:create_icecream' %}">Create Icecream</a></li>

        {% elif active_page == 'create icecream' %}
            <li class=""><a href="{% url 'taskboard:all_tasks' %}">All tasks</a></li>
            <li class=""><a href="{% url 'taskboard:create_task' %}">Create task</a></li>
            <li class=""><a href="{% url 'taskboard:edit_task' %}">Edit task</a></li>
            <li class=""><a href="{% url 'taskboard:icecream' %}">Icecream</a></li>
            <li class="active"><a href="{% url 'taskboard:create_icecream' %}">Create Icecream</a></li>

        {% elif active_page == 'Edit task' %}
            <li class=""><a href="{% url 'taskboard:all_tasks' %}">All tasks</a></li>
            <li class=""><a href="{% url 'taskboard:create_task' %}">Create task</a></li>
            <li class="active"><a href="{% url 'taskboard:edit_task' %}">Edit task</a></li>
            <li class=""><a href="{% url 'taskboard:icecream' %}">Icecream</a></li>
            <li class=""><a href="{% url 'taskboard:create_icecream' %}">Create Icecream</a></li>
        {% elif active_page == 'About task' %}
            <li class=""><a href="{% url 'taskboard:all_tasks' %}">All tasks</a></li>
            <li class=""><a href="{% url 'taskboard:create_task' %}">Create task</a></li>
            <li class=""><a href="{% url 'taskboard:edit_task' %}">Edit task</a></li>
            <li class=""><a href="{% url 'taskboard:icecream' %}">Icecream</a></li>
            <li class=""><a href="{% url 'taskboard:create_icecream' %}">Create Icecream</a></li>
        {% endif %}
        <li><a href="../../../../../Downloads/amado/product-details.html"></a></li>
        <li class=""><a href="cart.html"></a></li>
        <li><a href="../../../../../Downloads/amado/checkout.html"></a></li>
    </ul>
    <!-- Button Group -->
    <div class="amado-btn-group mt-30 mb-100">
        <span> </span>
        <span> </span>
    </div>
    <!-- Cart Menu -->
    <!-- Social Button -->
    <div class="social-info d-flex justify-content-between">
        <a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
        <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
        <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
        <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
    </div>
</nav>

templates/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav class='pagination_wrapper' aria-label="pagination">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.start_index }}" aria-label="Первая">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Предыдущая">
                <span class="page-link disabled">...</span>
            </a>
        </li>
        {% endif %}

        {% with start_page=page_obj.number|add:"-1" end_page=page_obj.number|add:"1" %}
        {% for page in page_obj.paginator.page_range %}
        {% if page >= start_page and page <= end_page %}
        <li class="page-item {% if page == page_obj.number %}active{% endif %}">
            <a class="page-link" href="?page={{ page }}">{{ page }}</a>
        </li>
        {% endif %}
        {% endfor %}
        {% endwith %}

        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Следующая">
                <span class="page-link disabled">...</span>
            </a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Последняя">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
        {% endif %}
    </ul>

</nav>
{% endif %}

templates/includes/statistic.html
<div class="col-12 col-lg-4">
    <div class="cart-summary">
        <h5>Total count: {{ total_tasks_count }}</h5>
        <ul class="summary-table">
            <li><span>not started:</span> <span>{{ not_started_tasks_count }}</span></li>
            <li><span>in progress:</span> <span>{{ in_process_tasks_count }}</span></li>
            <li><span>done:</span> <span>{{ done_tasks_count }}</span></li>
        </ul>
    </div>
</div>

templates/includes/subscribe.html
{% load static %}
<!-- ##### Newsletter Area Start ##### -->
    <section class="newsletter-area section-padding-100-0">
        <div class="container">
            <div class="row align-items-center">
                <!-- Newsletter Text -->
                <div class="col-12 col-lg-6 col-xl-7">
                    <div class="newsletter-text mb-100">
                        <h2>Subscribe for a <span>25% Discount</span></h2>
                        <p>Nulla ac convallis lorem, eget euismod nisl. Donec in libero sit amet mi vulputate consectetur. Donec auctor interdum purus, ac finibus massa bibendum nec.</p>
                    </div>
                </div>
                <!-- Newsletter Form -->
                <div class="col-12 col-lg-6 col-xl-5">
                    <div class="newsletter-form mb-100">
                        <form action="{% url 'taskboard:subscribe' %}" method="post">
                            {% csrf_token %}
                            <input type="email" name="email" class="nl-email" placeholder="Your E-mail">
                            <input type="submit" value="Subscribe">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ##### Newsletter Area End ##### -->

templates/includes/title.html
{% if title == 'Create new task' %}
    <title>Create new task</title>
{% elif title == 'All tasks' %}
    <title>All tasks</title>
{% elif title == 'About task' %}
    <title>About task</title>
{% elif title == 'Edit task' %}
    <title>Edit task</title>
{% endif %}