HomeWork/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hw_23Nov.urls')),
    path('', include('hw_23Nov_part2.urls')),
]

TaskManager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('TaskBoard.urls', namespace='taskboard'))

]
urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

accounts/urls.py
from django.urls import path, re_path
from django.contrib.auth.views import LoginView

from .views import UserCreateView, AllUsersView, UserDetailView, UsersByPeriodView, UserLoginView, reset_pass, new_pass

app_name = 'accounts'
urlpatterns = [
    re_path(r'^r\w{2}/$', UserCreateView.as_view(), name='registration'),
    re_path(r'^l\w*/$', UserLoginView.as_view(), name='login'),
    path('reset/', reset_pass, name='reset'),
    path('new_pass/<int:pk>/', new_pass, name='new_pass'),

    path('users/', AllUsersView.as_view(), name='users'),
    path('get_period/<int:year>/<int:month>/', UsersByPeriodView.as_view(), name='period'),
    path('userdetail/<int:user_id>/', UserDetailView.as_view(), name='user_detail')
]

bboard/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, re_path
from django.views.decorators.http import condition
from django.views.generic import ArchiveIndexView

from bboard.models import Bb
from bboard.views import BbCreateView, Categorylist, BbDetail, CreateComment, DeleteComment, AboutUs, Contacts, \
     BbRedirectView, BbEditView, edit, rubrics, bbs, Search, index, test_email, is_updated


app_name = 'bboard'

cache_page: object
urlpatterns = [
    re_path(r'^add/$', BbCreateView.as_view(), name='add'),
    re_path(r'^detail/(?P<bb_id>[0-9]+)/$', BbDetail.as_view(), name='detail'),
    path('rubrics/', rubrics, name='rubrics'),
    re_path(r'^rubric/(?P<rubric_id>[0-9]+)/$', Categorylist.as_view(), name='by_rubric'),
    re_path(r'^$', index, name='index'),
    re_path(r'^a\w{3}t/$', AboutUs.as_view(), name='about'),
    re_path(r'^c\w{6}s/$', Contacts.as_view(), name='contacts'),
    re_path(r'^create/(?P<bb_id>[0-9]+)/$', CreateComment.as_view(), name='c_create'),
    re_path(r'^delete/(?P<comment_id>[0-9]+)/(?P<bb_id>[0-9]+)/$', DeleteComment.as_view(), name='delete_comment'),
    path('update/<int:pk>/', edit, name='update'),
    path('bbs/<int:rubric_id>/', bbs, name='bbs'),
    path('year/<int:year>/', BbRedirectView.as_view(), name='redirect'),
    # path('<int:year>/<int:month>/', BbMonthView.as_view(), name='month'),
    path('mail/', test_email, name='test_email'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),



    path('search/', Search, name='search')
]

samplesite/urls.py
from django.contrib import admin
from django.urls import path,  include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bboard.urls', namespace='bboard')),
    path('authorization/', include('accounts.urls', namespace='accounts'))

]

urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

bboard/models.py
import uuid
from django.core import validators
from django.core.exceptions import ValidationError
from django.db import models
from precise_bbcode.fields import BBCodeTextField

is_all_posts_passive = False

class PositivePriceValidator():
    def __call__(self,val):
        if val < 0:
            raise ValidationError('Стоимость не должна быть меньше нуля', code='negative', params={'value':val})

def is_active():
    return is_all_posts_passive

def validate_even(val):
    if val % 2 !=0:
        raise ValidationError('Число %(value)s нечетное', code='odd', params={'value':val})

# class MinMaxValueValidator:
#     def __init__(self, min_value, max_value):
#         self.min_value = min_value
#         self.max_value = max_value
#
#     def __call__(self,val):
#         if val < self.min_value or val > self.max_value:
#             raise ValidationError('Число %(value)s должно находиться в диапазоне от: %(min)s до: %(max)s ',
#                                   code='out_of_range', params={'value':val, 'min': self.min_value, 'max': self.max_value})

class RubricQuerySet(models.QuerySet):
    def order_by_bb_count(self):
        return self.annotate(cnt=models.Count('bb')).order_by('-cnt')
class RubricManager(models.Manager):
    def get_queryset(self):
        # return super().get_queryset().order_by('order', 'name')
        return RubricQuerySet(self.model, using=self._db)
    def order_by_bb_count(self):
        # return super().get_queryset().annotate(cnt=models.Count('bb')).order_by('-cnt')
        return self.get_queryset().order_by_bb_count()


class BbManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().order_by('price')

class RubricQuerySet(models.QuerySet):
    def order_by_bb_count(self):
        return self.annotate(cnt=models.Count('bb')).order_by('-cnt')



class Rubric(models.Model):
    name = models.CharField(max_length=20, db_index=True, verbose_name='Название',unique=True)
    order = models.SmallIntegerField(default=0, db_index=True)#unique for day,/unique for month
    bbs = RubricManager()
    # objects = models.Manager()
    objects = RubricQuerySet.as_manager()
    # slug = models.SlugField (max_length = 160, unique = True)
    #db_index индексация поиска, бинарные деревья

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs): #вызывается в момент сохранения данных в базу данных
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs): #вызывается в момент удаления данных из базы данных
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return f"/{self.pk}/"

    class Meta:
        verbose_name_plural = 'Рубрики'
        verbose_name = 'Рубрика'
        ordering = ['order', 'name']
class Bb(models.Model):
    class Kinds(models.TextChoices):
        BUY = 'b','Куплю'
        SELL= 's', 'Продам'
        RENT = 'r', 'Аренда'
        PRESENT = 'p', 'Дар'
        __empty__ = 'Выберите тип объявления'
    '''KINDS = (
        ('b', 'Куплю'),
        ('s', 'Продам'),
        ('с', 'Обменяю')
    )'''
    '''KINDS = (
        ('Купля-продажа',(
         ('s', 'Продам'),
        ('b', 'Куплю'),
        )),
        ('Обмен',(
        ('с', 'Обменяю'),
        ))'''

    # KINDS = (
    #     (None, 'Выберите тип объявления')
    #     ('b', 'Куплю'),
    #     ('s', 'Продам'),
    #     ('с', 'Обменяю')
    # )

    class Features(models.TextChoices):
        NEW = 'n', 'Новый'
        USED = 'u', 'Б\у'
        ORDER = 'o', 'Под заказ'




    #kind = models.CharField(max_length=1, choices=KINDS,default='s')
    # kind = models.CharField(max_length=1, choices=KINDS,blank=True)
    kind = models.CharField(max_length=1, choices=Kinds.choices, default=Kinds.SELL)
    rubric = models.ForeignKey("Rubric", null=True, on_delete=models.PROTECT, #наименование поля, которое отображается, related_name = '' замена objects во view
                               #"Rubric" в ковычках, позволяет обращаться в любом порядке, раньше или позже кода строки без ковычек, значик модель должна быть реализована выше
                               verbose_name='Рубрика') # +helptext = '' помощь/описание без настройки не отображается

    title = models.CharField(max_length=50, verbose_name="Товар",validators=[validators.RegexValidator(regex='^.{4,}$')], error_messages= {'invalid':'Зачем вводишь некорректные данные?'})
    content = models.TextField(null=True, blank=True, verbose_name="Описание")
    # content = BBCodeTextField(null=True, blank=True, verbose_name="Описание")
    price = models.DecimalField(verbose_name="Цена",default=0, max_digits=12, decimal_places=2, validators=[validate_even])# +default= 0.0 дефолтное значение #
    is_active = models.BooleanField(default=is_all_posts_passive)
    published = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Опубликовано")#auto_now_add - заполнение поля текущим временем в момент создания не изменяется
    updated = models.DateTimeField(auto_now=True, db_index=True, verbose_name="Обновлено")
    feature = models.CharField(max_length=1, choices=Features.choices, default=Features.USED, verbose_name="Свойство")#auto_now - заполнение поля текущим временем в момент создания обновляемое
    by_price = BbManager()
    objects = models.Manager()
    #id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False) #editable=False вывод в форму)
    """типы полей:
    -charfield - текстовое поле (обязательно max_length)
    -textfield - текстовое поле (не обязательно max_length)
    -emailField (не обязательно max_lengt
    -urlField 
    -SlugField (max_length = 50, allow_unicode = True)
    -NullBooleanField
    -IntegerField
    -PositiveIntegerField (Small, Big)
    -BinaryField()
    -AutoField - для id
    -UUIDField"
    -"""



    def __str__(self):
        return f'{self.title}'

    """def clean(self):
        errors = {}
        if not self.content:
            errors['content'] = ValidationError('Укажите описание товара')
        if self.price and self.price < 0:
            errors['content'] = ValidationError('Цена должна быть больше нуля')
        if errors:
            raise ValidationError(errors)"""

    def clean_title(self):
        print("Не продаем бобров!")
        errors = {}
        if self.title == 'Бобёр':
            print("Проверка наименования")
            errors['content'] = ValidationError('Бобры не продаются')
            raise ValidationError(errors)

    def id_title(self):
        return f"{self.pk}_{self.title}"
    def id_price(self):
        sum = self.pk+self.price
        return sum
    def new_id(self):
        return f"id{self.pk}"

    def title_and_price (self):
        if self.price:
            return  f"{self.title}  {self.price:.2f} $"
        return self.title

    title_and_price.short_description = 'Название и цена' #только для админки


    class Meta:
        # доп настройки модели
        verbose_name_plural = 'Объявления'
        verbose_name = 'Объявление'
        ordering = ['title'] #можно несколько параметров
        # order_with_respect_to = 'rubric'


class Comments(models.Model):
    bb = models.ForeignKey("Bb", null=False, on_delete=models.CASCADE, verbose_name="Объявление")
    comment_creator = models.CharField(max_length=30, verbose_name="Автор")
    comment = models.CharField(max_length=500, verbose_name="Комментарий")
    issue_date = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Дата создания")
    def __str__(self):
        return f'{self.comment}'

    class Meta:
        # доп настройки модели
        verbose_name_plural = 'Комментарии'
        verbose_name = 'Комментарий'
        ordering = ['-issue_date'] #можно несколько параметров

templates/bb.html
{% extends "layout/basic.html" %}
{% load bbcode_tags %}
{% block title %}{{bb.title}}{% endblock %}

{% block content %}
<h2>{{bb.get_kind_display}}:</h2>
<h2>{{bb.title|capfirst}}</h2>
<h1>{{bb.price|default:"У товара нет цены"}}</h1>
<h3>bbcode bb.content</h3>
{% bbcode bb.content %}

<h3>bb.content|bbcode|safe</h3>
{{ bb.content|bbcode|safe }}

<h3>bb.content.rendered</h3>
{{ bb.content.rendered }} {# если прописали в модели #}


<h3>{{bb.content}}</h3>
<h4>{{bb.published}}<br></h4>

<h4>Комментарии:</h4>
<form  method = "post" action="{% url 'bboard:c_create' bb_id=bb.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Добавить комментарий">
</form>
<div class = "comments">
    {% for comment in comments %}
    <form  method = "post" action="{% url 'bboard:delete_comment' comment_id=comment.pk bb_id=bb.pk %}">
        {% csrf_token %}
        <span>Автор:{{comment.comment_creator}} ({{comment.issue_date}})</span>
        <div class = "comment_row">
            <textarea style="width: 1000px;" readonly>{{comment.comment}}</textarea>
            <input type="submit" value="Удалить">
        </div>
        </form>
    {% endfor %}
</div>
    <a href="{% url 'bboard:update' bb.pk %}"><button >Редактировать</button></a>
{% endblock %}

templates/by_rubric.html
{% extends "layout/basic.html" %}

{% block title %}{{ current_rubric.name }}{% endblock %}

{% block content %}
<h2>Рубрика: {{ current_rubric.name }}</h2>

{% for bb in bbs %}
<div>
    <h2>{{ bb.title }}</h2>
    <p>{{ bb.content }}</p>
    <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
</div>
{% endfor %}

{% endblock %}

templates/change_password.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Смена пароля</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css">
</head>
<body style="display: flex; flex-direction: column;align-items: center;margin-top: 200px;">
<h1>Смена пароля для {{ user.username }}</h1>
<div style="width:400px; height:400px; border:1px solid #d5d5d5; border-radius: 10px;">
    <form method="post" class="container mt-5">
        {% csrf_token %}
        {% if error_message %}
            <p>{{error_message}}</p>
        {% endif %}
        {{ form.as_p }}
        <input type="submit" value="Сохранить" class="btn btn-primary mt-3">
    </form>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
</body>
</html>

templates/child.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Дети</title>
</head>
<body>
    <p>ФИО: {{child.name}}</p>
    <p>Пол: {{child.gender}}</p>
    <p>Возраст: {{child.age}}</p>
    <p>Родители: {{child.parent}}</p>
</body>
</html>

templates/edit_task.html
{% extends "layout/basic.html" %}

templates/footer.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>About Us</title>
</head>
<body style = "background-color: #1b1b1b;color: white;">
    <header>
        <a href="{% url 'bboard:index' %}">Главная страница</a>
    </header>
    {% for str in content%}
    <p style = "font-size: 20px;">{{str}}</p>
    {% endfor %}
</body>
</html>

templates/index.html
{% extends "layout/basic.html" %}

{% load custom_filters %}
{% load bootstrap4 %}



{% block content %}

    <p>
    {% for d in date_list %}
        <a href="{% url 'bboard:month' year=d.year month=d.month|month_to_number  %}">
            {{ d.year }} - {{ d.month }}</a>
    {% endfor %}
    </p>
<div class="grid">
{% for bb in bbs %}
 <div class = 'content'>
    <h2>
        <a href="{% url 'bboard:detail' bb_id=bb.pk %}">
            {{ bb.title_and_price }}</a>
    </h2>
    <p>{{ bb.content }}</p>
    <p>
        <a href="{% url 'bboard:by_rubric' bb.rubric.pk %}">
            {{ bb.rubric.name }}</a>
    </p>
    <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
</div>
{% endfor %}
</div>
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Авторизация</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css">
</head>
<body style="display: flex; flex-direction: column;align-items: center;margin-top: 200px;">
<h1>Войти</h1>
<div style="width:400px; height:400px; border:1px solid #d5d5d5; border-radius: 10px;">
    {% if request.user.is_authenticated %}
        <p>Пользователь уже авторизован</p>
    {% else %}
        <form method="post" class="container mt-5">
            {% csrf_token %}
            {{ form.as_p }}
            {% if error_message %}
                <p>{{error_message}}</p>
            {% endif %}
            <input type="submit" value="Вход" class="btn btn-primary mt-3">
        </form>
        <a href="{% url 'accounts:reset' %}">Забыли пароль?</a>
    {% endif %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
</body>
</html>

templates/object_passport.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
        <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->
        <Title>Объект</Title>
    </head>
    <body>
        <style>
            body {
                display: flex;
                flex-direction: column;
                justify-content: space-between;
                padding: 0px;
                margin: 0px;
                height: 100vh;
                width: 100vw;
                align-items: center;
                background-color: #404040;
            }
            .photo_description{
                margin-top: 20px;
                width: 500px;
                border: 1px solid #4f4f4f;
                display: flex;
                flex-direction: column;
                justify-content: space-between;
                align-items: center;
                border-radius: 10px;

            }
            .photo{
                width: 400px;
                height: 400px;
                background-color: #272727;
                border-radius: 10px;
            }
            .description{
                margin-top: 20px;
                width: 460px;
                min-height:20px;
                background-color: #272727;
                padding-top: 20px;
                padding-left: 20px;
                padding-right: 20px;
                padding-bottom: 20px;
                border-radius: 10px;
                color: white;
                font-size: 18px;

            }
            .general_info{
                width: 400px;
                height: 400px;
                background-color: #272727;
                margin-left: 20px;
                border-radius: 10px;
                padding-left: 20px;
                color: white;
                font-size: 18px;
                margin-top: 20px;
            }
            header{
                height: 80px;
                width: 100vw;
                display: flex;
                justify-content: space-around;
                background-color: #272727;
                align-items: center;

            }
            .btn{
                height: 43px;
                width: 200px;
                border-radius: 10px;
                background-color: rgba(0,0,0,0);
                color: white;
                font-size: 18px;
            }
            .btn:hover{
                background-color: #3AB2C3;
                color: white;
                font-size: 18px;
            }
            footer{
                height: 80px;
                width: 100vw;
                display: flex;
                justify-content: space-around;
                background-color: #272727;
                align-items: center;
                color: white;
                font-size: 18px;
                margin-top: 20px;
            }
            .content{
                width: 60vw;
                display: flex;
                flex-direction: row;
                justify-content: space-between;
                align-items: flex-start;
            }
        </style>
        <header>
            <a href=""><button class = "btn">title</button></a>
            <a href=""><button class = "btn">title</button></a>
            <a href=""><button class = "btn">title</button></a>
            <a href=""><button class = "btn">title</button></a>
        </header>
        <div class="content">
            <div class="general_info">
                <p>id: {{object.id}}</p>
                <p>Пользователь {{object.userId}}:</p>
                <p>Дата:</p>
                <p>Статус: {{object.completed}}</p>
            </div>
            <div class = "photo_description">
                <div class = "photo">
                    <img src = "#" alt="Здесь должна быть картинка">
                </div>
                <div class = "description">Описание: {{object.title}}</div>
            </div>
        </div>
        <footer>
            <a>О нас</a>
            <a>Контакты</a>
            <a>Адрес</a>
            <a>Партнерам</a>
        </footer>
    </body>
</html>

templates/reset_pass.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Сброс пароля</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css">
</head>
<body style="display: flex; flex-direction: column;align-items: center;margin-top: 200px;">
<h1>Сбросить пароль</h1>
<div style="width:400px; height:400px; border:1px solid #d5d5d5; border-radius: 10px;">
    <form method="post" class="container mt-5">
        {% csrf_token %}
        {% if error_message %}
            <p>{{error_message}}</p>
        {% endif %}
        <p>Укажите e-mail, на который будет отправлено сообщение</p>
        <input type="email" name="email" class="">
        <input type="submit" value="Отправить письмо" class="btn btn-primary mt-3">
    </form>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
</body>
</html>

templates/rubrics.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}

{% block title %}Изменение рубрик{% endblock %}

{% block content %}
<h2>Изменение рубрик</h2>
    <form  method = "post">
    {% csrf_token %}
    {% bootstrap_formset formset %}
    {% buttons submit='Сохранить' reset='Сбросить' %}{% endbuttons form layout='inline' field_class='col-md-10' required_css_class='has-error'%}

    </form>
{% endblock %}

templates/search.html
{% extends "layout/basic.html" %}

{% block title %}Поиск{% endblock %}

{% block content %}
<h2>Поиск</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Поиск">
    </form>
{% endblock %}

templates/update.html
{% extends "layout/basic.html" %}

{% block title %}Изменение объявления{% endblock %}

{% block content %}
<h2>Изменение объявления</h2>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                    {{ message }}
                </li>
            {% endfor %}
        </ul>
    {% endif %}
    {% if form.is_multipart %}
        <form  method = "post" enctype="multipart/form-data">
    {% else %}
        <form  method = "post">
    {% endif %}
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {% if form.non_fields_errors %}
            <ul>
                {% for error in form.non_fields_errors %}
                    <li>{{ error|escape }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        {% for field in form.visible_fields %}
            {% if field.errors %}
                   {% for error in field.errors %}
                       <li>{{ error|escape }}</li>
                    {% endfor %}
            {% endif %}
            <p>{{ field.label_tag }}<br>{{ field }}<br>{{ field.help_text }}</p>
        {% endfor %}
        <input type="hidden" name="signed_pk" value="{{ signed_pk }}">
        <input type="submit" value="Изменить">
        </form>

{% endblock %}

templates/users.html
{% load static %}
{% load custom_filters %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>All Users</title>
</head>
<body class = "users_body">
    <header>
        <a href="{% url 'bboard:index' %}">Главная страница</a>
    </header>
        <p>
            {% for period in date_list %}
                <a href="{% url 'accounts:period' year=period.year month=period.month|month_to_number  %}">
                {{ period.year }}:{{ period.month }}</a>
            {% endfor %}
        </p>
        <div class = "users">
        {% for user in users %}
            <form action="{% url 'accounts:user_detail' user.pk %}">
                <div class = "user">
                    <p>Логин: {{user.login}}</p>
                    <p>e-mail: {{user.email}}</p>
                    <p>Дата-рождения: {{user.birth_date}}</p>
                    <p>Статус: {% if user.is_blocked == False %} Активен {% else %} Заблокирован {% endif %}</p>
                    <input type="submit" value="Подробнее">
                </div>
            </form>
        {% endfor %}
        </div>

</body>
</html>