HomeWork/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hw_23Nov.urls')),
    path('', include('hw_23Nov_part2.urls')),
]

TaskManager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('TaskBoard.urls', namespace='taskboard'))

]
urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

bboard/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, re_path
from django.views.decorators.http import condition
from django.views.generic import ArchiveIndexView

from bboard.models import Bb
from bboard.views import BbCreateView, Categorylist, BbDetail, CreateComment, DeleteComment, AboutUs, Contacts, \
     BbRedirectView, BbEditView, edit, rubrics, bbs, Search, index, test_email, is_updated


app_name = 'bboard'

cache_page: object
urlpatterns = [
    re_path(r'^add/$', BbCreateView.as_view(), name='add'),
    re_path(r'^detail/(?P<bb_id>[0-9]+)/$', BbDetail.as_view(), name='detail'),
    path('rubrics/', rubrics, name='rubrics'),
    re_path(r'^rubric/(?P<rubric_id>[0-9]+)/$', Categorylist.as_view(), name='by_rubric'),
    re_path(r'^$', index, name='index'),
    re_path(r'^a\w{3}t/$', AboutUs.as_view(), name='about'),
    re_path(r'^c\w{6}s/$', Contacts.as_view(), name='contacts'),
    re_path(r'^create/(?P<bb_id>[0-9]+)/$', CreateComment.as_view(), name='c_create'),
    re_path(r'^delete/(?P<comment_id>[0-9]+)/(?P<bb_id>[0-9]+)/$', DeleteComment.as_view(), name='delete_comment'),
    path('update/<int:pk>/', edit, name='update'),
    path('bbs/<int:rubric_id>/', bbs, name='bbs'),
    path('year/<int:year>/', BbRedirectView.as_view(), name='redirect'),
    # path('<int:year>/<int:month>/', BbMonthView.as_view(), name='month'),
    path('mail/', test_email, name='test_email'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),



    path('search/', Search, name='search')
]

samplesite/urls.py
from django.contrib import admin
from django.urls import path,  include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bboard.urls', namespace='bboard')),
    path('authorization/', include('accounts.urls', namespace='accounts'))

]

urlpatterns += [
    path('captcha/', include('captcha.urls')),
]

templates/layout/basic.html
{% load static %}
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Главная{% endblock %} :: Доска объявлений</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">

    <link rel="stylesheet" href="{{ STATIC_URL }}style.css">
</head>
<body class = 'body'>
{% include 'includes/inc_main_menu.html' %}
    <div class = 'rubrics'>
     {% for rubric in rubrics %}
        {% with bb_count=rubric.cnt %}
        <a href="{% url 'bboard:by_rubric' rubric.pk %}{#{ rubric.get_absolute_url }#}">
            {% filter force_escape|upper %}
            {{ rubric }} ({{bb_count}})
            {% endfilter %}
        </a>
        {% endwith %}
    {% endfor %}
    </div>
    <div class = "main">
        <div class = 'top_ann'>Ваши объявления могут быть в топе</div>
        <section>
            {% block content %}
            <p>Контент из basic.html</p>
            {% endblock %}
        </section>
        <div class = 'advert'>Здесь может быть ваша реклама</div>
    </div>
    <footer>&copy;1982 &ndash; {% now 'Y' %}
        <a href = "{% url 'bboard:about' %}">О нас </a>
        <a href = "{% url 'bboard:contacts' %}">Контакты </a>
    </footer>

    {% bootstrap_javascript jquery='full' %}
</body>
</html>